spring:
    kafka:
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        consumer:
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            properties:
                spring.json.trusted.packages: "*"
    cloud:
        config:
            uri: http://config-server:8888  # Адрес Config Server
            name: kafka-consumer  # Имя конфигурационного файла для kafka-consumer в Config Server
        stream:
            kafka:
                binder:
                    brokers: kafka:9092  # Адрес Kafka-брокера
                    default-broker-port: 9092
                    zkNodes: zookeeper:2181
                bindings:
                    input:  # Канал входящих сообщений для консюмера
                        destination: producer-topic  # Топик, который kafka-consumer будет слушать
                        contentType: application/json
                        group: consumer-group  # Группа консумеров для совместной обработки сообщений

eureka:
    client:
        service-url:
            defaultZone: http://eureka-server:8761/eureka/
    instance:
        prefer-ip-address: true
        lease-renewal-interval-in-seconds: 10
        lease-expiration-duration-in-seconds: 30

logging:
    level:
        root: INFO
