server:
  port: 8081

spring:
    config:
      name: kafka-producer 
    kafka:
      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      consumer:
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        properties:
          spring.json.trusted.packages: "*"
    stream:
      kafka:
        binder:
          brokers: localhost:9092  
          default-broker-port: 9092
          zkNodes: localhost:2181
        bindings:
          output:  
            destination: producer-topic  
            contentType: application/json

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

logging:
  level:
    root: INFO  
