server:
  port: 8081

spring:
  application:
    name: kafka-producer
  cloud:
    config:
      uri: http://config-server:8888  
      name: kafka-producer 
    stream:
      kafka:
        binder:
          brokers: kafka:9092  
          default-broker-port: 9092
          zkNodes: zookeeper:2181
        bindings:
          output:  
            destination: producer-topic  
            contentType: application/json

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/  
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

logging:
  level:
    root: INFO  
